# knn distance calculation

### First L2 Eucledian distance, then compare with L1 Manhatten distance.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline
# Auto reload external python files
%load_ext autoreload
%autoreload 2

In [2]:
import foo
foo.some_function()
#  Rerun cell after changing foo.py.  
#  New value should print if "%autoreload" magic is working.

40

### Markdown Cell, showing local image.
Jennifer Lawrence, 32x32x3.  

<img src="jlaw.png" align="left" width="300">


In [3]:
# code for inserting a local image file in a Markdown Format Cell, uses old html, not HTML5.
# <img src="jlaw.png" align="left" width="300">

### L2 distance calculation

In [35]:
# Simplest test case with 2 points X1 and X2 as list types.
X1 = [0, 2, 4, 6]
X2 = [0, -1, -2, -3]
dist = (X1[2]-X2[2])**2
print(dist)
dist = (X1[3]-X2[3])**2
print(dist)

36
81


In [36]:
dlist = []
for i in range(4):
    var = (X1[i] - X2[i])**2
    dlist.append(var)
    print(dlist)

[0]
[0, 9]
[0, 9, 36]
[0, 9, 36, 81]


In [37]:
type(dlist)


list

In [38]:
(sum(dlist))**0.5

11.224972160321824

#### Numpy distance calculation

In [39]:
#  Calculate distance using numpy.
# First convert X1 and X2 from list to np.array type.
a = np.array(X1)
b = np.array(X2)

np.sqrt(np.sum((a-b)**2))
# Also gives same answer as above, 11.2249
# Element by element operation on a array and b array.

11.224972160321824

### Load test data, first 10 data rows, first 10 labels

In [52]:
# Load from file, previously saved numpy arrays.
# first 10 data rows, first 10 labels.

arr10 = np.load("arr10.npy")
labels10 = np.load("labels10.npy")
print(arr10, '\n', labels10)
print(len(arr10))

[[ 59  43  50 ... 140  84  72]
 [154 126 105 ... 139 142 144]
 [255 253 253 ...  83  83  84]
 ...
 [ 28  30  33 ... 100  99  96]
 [134 131 128 ... 136 137 138]
 [125 110 102 ...  82  84  86]] 
 [6 9 9 4 1 1 2 7 8 3]
10


In [70]:
#  Calculate distance using numpy, first 2 array elemets.
#   test on just first 5 cells in each array.
# Need to use np.subtract instead of "-" which gives wrong result.
#  CIFAR10 data is uint8, unsigned interger 0 to 255.
#  Difference calculation is not base 10.
#  For Math distance, need to convert uint8 to double or numeric type first!

a1 = np.array(arr10[0][0:2], dtype='int8') 
b1 = np.array(arr10[1][0:2], dtype='int8')
result1 = np.subtract(b1, a1) 
print("result", result1, "A:", a1, "B:", b1)

#a2 = np.array([132, 131, 128])
#b2 = np.array([125, 110, 102])

#result = np.subtract(b2, a2)
#print(result, a2, b2)
# Out>  [59 43 50 68 98] [154 126 105 102 125] [161 173 201 222 229]

result [95 83] A: [59 43] B: [-102  126]


#### uint8 is really messing up my subtraction!  

#### Try again with Reload and divde uint8 numbers by 255.0 to rebase to base-1.

### Load from file, previously saved numpy arrays.  
first 10 data rows, first 10 labels.

In [74]:
# Reload from file arr10, labels10.

arr10 = np.load("arr10.npy")
labels10 = np.load("labels10.npy")
print(arr10, '\n', labels10)
print(len(arr10))

[[ 59  43  50 ... 140  84  72]
 [154 126 105 ... 139 142 144]
 [255 253 253 ...  83  83  84]
 ...
 [ 28  30  33 ... 100  99  96]
 [134 131 128 ... 136 137 138]
 [125 110 102 ...  82  84  86]] 
 [6 9 9 4 1 1 2 7 8 3]
10


In [77]:
row0 = arr10[0]/255.0
print(arr10[0], row0)
# Results are fractions, 0.xxx

[ 59  43  50 ... 140  84  72] [0.23137255 0.16862745 0.19607843 ... 0.54901961 0.32941176 0.28235294]


In [78]:
row1 = arr10[1]/255.0
print(arr10[1], row1)

[154 126 105 ... 139 142 144] [0.60392157 0.49411765 0.41176471 ... 0.54509804 0.55686275 0.56470588]


#### Now calculate L2 distance, after rebasing.

In [86]:
diff = row0 - row1
print(diff)
diff = row1 - row0
print(diff)
# OK, finally math works!

[-0.37254902 -0.3254902  -0.21568627 ...  0.00392157 -0.22745098
 -0.28235294]
[ 0.37254902  0.3254902   0.21568627 ... -0.00392157  0.22745098
  0.28235294]


#### use numpy after converting uint8 to base-1.

In [93]:
#  Calculate distance using numpy.
# First convert from uint8 to base-1.
a = arr10[0]/255.0
b = arr10[1]/255.0

#a = arr10[0][0:3]/255.0
#b = arr10[1][0:3]/255.0

print("a-b", a-b)
print("sum", np.sum(a-b))
print("sqrt", np.sqrt(np.sum((a-b)**2)))

# Element by element operation on a array and b array.

a-b [-0.37254902 -0.3254902  -0.21568627 ...  0.00392157 -0.22745098
 -0.28235294]
sum -324.06666666666666
sqrt 17.40757457089783


#### Compare to without rebasing, keeping at uint8.

In [94]:
# Uses uint8 in arrays
a = arr10[0]
b = arr10[1]

print("a-b", a-b)
print("sum", np.sum(a-b))
print("sqrt", np.sqrt(np.sum((a-b)**2)))

# Element by element operation on a array and b array.

a-b [161 173 201 ...   1 198 184]
sum 407859
sqrt 565.5024314713421


In [95]:
# Okay, rebasing is necessary.  Get totally different results.

### Now calculate all 10 rows.

In [21]:
# Calculate distance between row1 and other 9 rows.
# Store result in distance.

import numpy as np
# Reload sample data from file.
arr10 = np.load("arr10.npy")
labels10 = np.load("labels10.npy")

# first row, rebased to base-1.
# a = arr10[0]/255.0
# i = 0

# Loop over 9 remaining rows, calculate distance.


distance = []
dist2 = []

for i in range(0, 10):
    a = arr10[i]/255.0
    for j in range(0, 10):
        b = arr10[j]/255.0
        dist = np.sqrt(np.sum((a-b)**2))
        # print(i, j, "sqrt", dist)
        dist2.append([i, j, dist])
    
# print(dist2)

In [38]:
arr = np.asarray(dist2)
arr3d = np.reshape(arr, (10, 10, 3))
print(arr3d[0:5])

[[[ 0.          0.          0.        ]
  [ 0.          1.         17.40757457]
  [ 0.          2.         24.60133841]
  [ 0.          3.         10.60761697]
  [ 0.          4.         18.14730998]
  [ 0.          5.         14.58365678]
  [ 0.          6.         15.20040723]
  [ 0.          7.         16.84254604]
  [ 0.          8.         22.53144584]
  [ 0.          9.         19.64496486]]

 [[ 1.          0.         17.40757457]
  [ 1.          1.          0.        ]
  [ 1.          2.         22.95526499]
  [ 1.          3.         17.77008186]
  [ 1.          4.         17.32491145]
  [ 1.          5.         19.88553094]
  [ 1.          6.         16.25368855]
  [ 1.          7.         18.94330155]
  [ 1.          8.         19.54055041]
  [ 1.          9.         22.2373665 ]]

 [[ 2.          0.         24.60133841]
  [ 2.          1.         22.95526499]
  [ 2.          2.          0.        ]
  [ 2.          3.         24.41791087]
  [ 2.          4.         20.178335

In [33]:
# Convert 2d numpy array into numpy matrix.


NameError: name 'shape' is not defined

### L1 distance calculation

In [ ]:
# Esc, m, Enter -- to change currently edition cell to markdown.

**This is a markdown cell.**